#!/bin/bash
# normdate--Noralises month field in date specification to 3 letters,
#   first letter capitalised.
#   Exit with 0 on success.

monthToName() {
  # Sets the 'month' variable to the appropriate value.
  case $1 in
    1 ) month="Jan"  ;;  2 ) month="Feb"  ;;
    3 ) month="Mar"  ;;  4 ) month="Apr"  ;;
    5 ) month="May"  ;;  6 ) month="Jun"  ;;
    7 ) month="Jul"  ;;  8 ) month="Aug"  ;;
    9 ) month="Sep"  ;;  10) month="Oct"  ;;
    11) month="Nov"  ;;  12) month="Dec"  ;;
    * ) echo "$0: Unknown month value $1" >&2
        exit 1
  esac
  return 0
}

if [ $# -eq 1 ] ; then
  set -- $(echo $1 | sed 's:[/-]: :g')
fi

# Input validation
if [ $# -ne 3 ] ; then
  echo "Usage: $0 MONTH DAY YEAR" >&2
  echo "Formats are August 3 1962 and 8 3 1962" >&2
  exit 1
fi

if [ $3 -le 999 ] ; then
    echo "$0: Expected 4 digit year value." >&2
    exit 1
fi

# Is it a month input format?
if [ -z $(echo $1 | sed 's/[[:digit:]]//g') ]; then
  monthToName $1
else
  month="$(echo $1 | cut -c1 | tr '[:lower:]' '[:upper:]')"
  month="$month$(echo $1 | cut -c2-3 | tr '[:upper:]' '[:lower:]')"
fi

echo $month $2 $3

exit 0
